language: node_js
node_js:
  - '8'
addons:
  sauce_connect:
    username: williamcardozo
    access_key: 05062c60-da0e-4995-8d4d-c9d552593729
cache:
  directories:
    - node_modules
before_install:
  - npm install
script:
  - npm run test
